### ISSUE TITLE
Checkpoint for forwarding

### ISSUE THREAD

**Issue by guohaoxiang** [FENGGENYU/CAPRI-Net#1]
Hi, Fenggen,
Thanks for releasing the code, it's really helpful.

After setting up down the environment and unzipping data and pretrained weights under the root folder, I try to forward the network following your instruction:

python test.py -e abc_voxel -g 0 -p 2 -c best_stage2 --test --voxel --start 0 --end 1 

But I got the following error:

![image](https://user-images.githubusercontent.com/29721619/179738426-c0a992a4-62c3-4441-8507-e1dfce326222.png)

It seems that the provided ./abc_voxel/ModelParameters/initial.pth is not enough for network forwarding, Can you provide the complete checkpoint so that we can forward all test data directly?

Thank you in advance.

**Comment by FENGGENYU** [comment]
Hi, haoxiang.

You can get this parameter by running fine-tuning.py as the instruction showed.

I didn't upload these parameters of each shape after fine-tuning, because the total parameters from all shapes is too large for my google drive space.

Anyway, I uploaded the parameters from the voxel2CSG experiments for ABC shapes here(about 36 GB), you can run test.py on them.

https://drive.google.com/file/d/1KGwbX-Q8tQdMBGB7gx_1D_s5YidOB-ze/view?usp=sharing

**Comment by guohaoxiang** [comment]
Thanks, Fenggen. You are awesome! That's really helpful. 

It seems that the provided data and checkpoint are all about ABC dataset. Could you please also share the data and checkpoints of ShapeNet? I can conduct the fine-tuning by myself.

**Comment by FENGGENYU** [comment]
Please check the updated news.

**Comment by guohaoxiang** [comment]
Thanks, fenggen. I've succussfully forward CAPRI-Net.
A few suggestions:
1. https://github.com/FENGGENYU/CAPRI-Net/blob/6ed83d618c45d498c78aa4f733137888b08f142d/fine-tuning.py#L144 here SurfaceSamples(data_source) should be changed to SurfaceSamples(data_source, True) for testing.
2. https://github.com/FENGGENYU/CAPRI-Net/blob/6ed83d618c45d498c78aa4f733137888b08f142d/utils/dataloader.py#L21 here "names.npz" should be changed to "test_names.npz".
3. PyMCubes, h5py, plyfile, pymesh should be added in the environments.

Best,
Haoxiang Guo
